name: build
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildx:
    runs-on: self-hosted
    timeout-minutes: 4320
    steps:
      - name: Mask Cache Registry Secrets
        run: |
          echo "::add-mask::$CACHE_REGISTRY_URL"
          echo "::add-mask::$CACHE_REGISTRY_USERNAME"
          echo "::add-mask::$CACHE_REGISTRY_PASSWORD"
          echo "CACHE_REGISTRY_URL=$CACHE_REGISTRY_URL" >> $GITHUB_ENV
          echo "CACHE_REGISTRY_USERNAME=$CACHE_REGISTRY_USERNAME" >> $GITHUB_ENV
          echo "CACHE_REGISTRY_PASSWORD=$CACHE_REGISTRY_PASSWORD" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Version
        id: get_version
        uses: dhkatz/get-version-action@v3.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          name: shiny-builder
          cleanup: false

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Cache Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.CACHE_REGISTRY_URL }}
          username: ${{ env.CACHE_REGISTRY_USERNAME }}
          password: ${{ env.CACHE_REGISTRY_PASSWORD }}

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Build and push shiny
        uses: docker/build-push-action@v7
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          target: shiny
          push: true
          tags: |
            hvalev/shiny-server-arm:${{ steps.get_version.outputs.version }}
            hvalev/shiny-server-arm:latest
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY_URL }}/shiny-cache:buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY_URL }}/shiny-cache:buildcache,mode=max

      - name: Build and push shiny with devtools
        uses: docker/build-push-action@v7
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          target: shiny-with-devtools
          push: true
          tags: |
            hvalev/shiny-server-arm:devtools-${{ steps.get_version.outputs.version }}
            hvalev/shiny-server-arm:devtools-latest
          cache-from: type=registry,ref=${{ env.CACHE_REGISTRY_URL }}/shiny-cache:buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REGISTRY_URL }}/shiny-cache:buildcache,mode=max

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: hvalev/shiny-server-arm
